import { createHash } from "node:crypto";

import type { ChallengeTemplateRecord, Rarity } from "@/lib/types";

type ChallengeDraft = Omit<ChallengeTemplateRecord, "id" | "environmentType"> & {
  slug: string;
};

function challengeId(slug: string) {
  const hash = createHash("sha1").update(slug).digest("hex");
  return `${hash.slice(0, 8)}-${hash.slice(8, 12)}-${hash.slice(12, 16)}-${hash.slice(16, 20)}-${hash.slice(20, 32)}`;
}

function createChallenge(draft: ChallengeDraft): ChallengeTemplateRecord {
  return {
    id: challengeId(draft.slug),
    title: draft.title,
    description: draft.description,
    type: draft.type,
    environmentType: "any",
    xpReward: draft.xpReward,
    targetCount: draft.targetCount,
    conditionType: draft.conditionType,
  };
}

function classChallenge(
  slug: string,
  title: string,
  description: string,
  type: "daily" | "weekly" | "achievement",
  className: string,
  targetCount: number,
  xpReward: number,
) {
  return createChallenge({
    slug,
    title,
    description,
    type,
    targetCount,
    xpReward,
    conditionType: `capture_class:${className}`,
  });
}

function rarityChallenge(
  slug: string,
  title: string,
  description: string,
  type: "daily" | "weekly" | "achievement",
  rarity: Rarity,
  targetCount: number,
  xpReward: number,
  exact = false,
) {
  return createChallenge({
    slug,
    title,
    description,
    type,
    targetCount,
    xpReward,
    conditionType: `${exact ? "capture_rarity_exact" : "capture_rarity_min"}:${rarity}`,
  });
}

function levelChallenge(
  slug: string,
  title: string,
  description: string,
  level: number,
  xpReward: number,
) {
  return createChallenge({
    slug,
    title,
    description,
    type: "achievement",
    targetCount: level,
    xpReward,
    conditionType: `reach_level:${level}`,
  });
}

const dailyChallenges: ChallengeTemplateRecord[] = [
  createChallenge({
    slug: "daily-field-note",
    title: "Field Note",
    description: "Capture any animal today.",
    type: "daily",
    targetCount: 1,
    xpReward: 15,
    conditionType: "capture_any",
  }),
  createChallenge({
    slug: "daily-double-sighting",
    title: "Double Sighting",
    description: "Capture 2 animals today.",
    type: "daily",
    targetCount: 2,
    xpReward: 30,
    conditionType: "capture_any",
  }),
  createChallenge({
    slug: "daily-triple-trek",
    title: "Triple Trek",
    description: "Capture 3 animals today.",
    type: "daily",
    targetCount: 3,
    xpReward: 45,
    conditionType: "capture_any",
  }),
  classChallenge(
    "daily-bird-watch",
    "Bird Watch",
    "Find a bird species today.",
    "daily",
    "Aves",
    1,
    25,
  ),
  rarityChallenge(
    "daily-shiny-find",
    "Shiny Find",
    "Capture an Uncommon or better species today.",
    "daily",
    "uncommon",
    1,
    35,
  ),
  createChallenge({
    slug: "daily-safari-sprint",
    title: "Safari Sprint",
    description: "Capture 4 animals today.",
    type: "daily",
    targetCount: 4,
    xpReward: 60,
    conditionType: "capture_any",
  }),
  createChallenge({
    slug: "daily-trailblazer",
    title: "Trailblazer",
    description: "Capture 5 animals today.",
    type: "daily",
    targetCount: 5,
    xpReward: 80,
    conditionType: "capture_any",
  }),
  classChallenge(
    "daily-feather-pair",
    "Feather Pair",
    "Capture 2 bird species today.",
    "daily",
    "Aves",
    2,
    40,
  ),
  classChallenge(
    "daily-bird-chorus",
    "Bird Chorus",
    "Capture 3 bird species today.",
    "daily",
    "Aves",
    3,
    60,
  ),
  classChallenge(
    "daily-mammal-mark",
    "Mammal Mark",
    "Find a mammal today.",
    "daily",
    "Mammalia",
    1,
    25,
  ),
  classChallenge(
    "daily-mammal-patrol",
    "Mammal Patrol",
    "Capture 2 mammals today.",
    "daily",
    "Mammalia",
    2,
    45,
  ),
  classChallenge(
    "daily-mammal-moment",
    "Mammal Moment",
    "Capture 3 mammals today.",
    "daily",
    "Mammalia",
    3,
    68,
  ),
  classChallenge(
    "daily-bug-hunt",
    "Bug Hunt",
    "Find an insect today.",
    "daily",
    "Insecta",
    1,
    22,
  ),
  classChallenge(
    "daily-bug-brigade",
    "Bug Brigade",
    "Capture 2 insects today.",
    "daily",
    "Insecta",
    2,
    38,
  ),
  classChallenge(
    "daily-insect-index",
    "Insect Index",
    "Capture 3 insects today.",
    "daily",
    "Insecta",
    3,
    58,
  ),
  classChallenge(
    "daily-frog-finder",
    "Frog Finder",
    "Find an amphibian today.",
    "daily",
    "Amphibia",
    1,
    28,
  ),
  classChallenge(
    "daily-scale-scan",
    "Scale Scan",
    "Find a reptile today.",
    "daily",
    "Reptilia",
    1,
    28,
  ),
  createChallenge({
    slug: "daily-class-hop",
    title: "Class Hop",
    description: "Capture 2 different animal classes today.",
    type: "daily",
    targetCount: 2,
    xpReward: 45,
    conditionType: "capture_distinct_class",
  }),
  createChallenge({
    slug: "daily-habitat-hopper",
    title: "Habitat Hopper",
    description: "Capture 3 different animal classes today.",
    type: "daily",
    targetCount: 3,
    xpReward: 65,
    conditionType: "capture_distinct_class",
  }),
  rarityChallenge(
    "daily-bright-bundle",
    "Bright Bundle",
    "Capture 2 Uncommon or better species today.",
    "daily",
    "uncommon",
    2,
    55,
  ),
  rarityChallenge(
    "daily-rarity-rush",
    "Rarity Rush",
    "Capture 3 Uncommon or better species today.",
    "daily",
    "uncommon",
    3,
    75,
  ),
  rarityChallenge(
    "daily-rare-encounter",
    "Rare Encounter",
    "Find a Rare or better species today.",
    "daily",
    "rare",
    1,
    70,
  ),
  rarityChallenge(
    "daily-rare-pair",
    "Rare Pair",
    "Capture 2 Rare or better species today.",
    "daily",
    "rare",
    2,
    110,
  ),
  rarityChallenge(
    "daily-epic-scout",
    "Epic Scout",
    "Find an Epic or better species today.",
    "daily",
    "epic",
    1,
    120,
  ),
  rarityChallenge(
    "daily-common-census",
    "Common Census",
    "Capture 3 Common species today.",
    "daily",
    "common",
    3,
    30,
    true,
  ),
  rarityChallenge(
    "daily-uncommon-focus",
    "Uncommon Focus",
    "Capture exactly 1 Uncommon species today.",
    "daily",
    "uncommon",
    1,
    45,
    true,
  ),
  rarityChallenge(
    "daily-rare-precision",
    "Rare Precision",
    "Capture exactly 1 Rare species today.",
    "daily",
    "rare",
    1,
    95,
    true,
  ),
  createChallenge({
    slug: "daily-dawn-dash",
    title: "Dawn Dash",
    description: "Capture 2 animals today.",
    type: "daily",
    targetCount: 2,
    xpReward: 32,
    conditionType: "capture_any",
  }),
  createChallenge({
    slug: "daily-pocket-parade",
    title: "Pocket Parade",
    description: "Capture 3 animals today.",
    type: "daily",
    targetCount: 3,
    xpReward: 48,
    conditionType: "capture_any",
  }),
  createChallenge({
    slug: "daily-sunset-survey",
    title: "Sunset Survey",
    description: "Capture 4 animals today.",
    type: "daily",
    targetCount: 4,
    xpReward: 62,
    conditionType: "capture_any",
  }),
];

const weeklyChallenges: ChallengeTemplateRecord[] = [
  createChallenge({
    slug: "weekly-five-finds",
    title: "Five Finds",
    description: "Capture 5 animals this week.",
    type: "weekly",
    targetCount: 5,
    xpReward: 70,
    conditionType: "capture_any",
  }),
  createChallenge({
    slug: "weekly-ten-tally",
    title: "Ten Tally",
    description: "Capture 10 animals this week.",
    type: "weekly",
    targetCount: 10,
    xpReward: 130,
    conditionType: "capture_any",
  }),
  createChallenge({
    slug: "weekly-class-collector",
    title: "Class Collector",
    description: "Capture 3 different animal classes this week.",
    type: "weekly",
    targetCount: 3,
    xpReward: 100,
    conditionType: "capture_distinct_class",
  }),
  rarityChallenge(
    "weekly-rare-encounter",
    "Rare Encounter",
    "Find a Rare or better species this week.",
    "weekly",
    "rare",
    1,
    140,
  ),
  classChallenge(
    "weekly-bird-binge",
    "Bird Binge",
    "Capture 3 bird species this week.",
    "weekly",
    "Aves",
    3,
    120,
  ),
  createChallenge({
    slug: "weekly-biome-blender",
    title: "Biome Blender",
    description: "Capture 4 different animal classes this week.",
    type: "weekly",
    targetCount: 4,
    xpReward: 160,
    conditionType: "capture_distinct_class",
  }),
  rarityChallenge(
    "weekly-rare-run",
    "Rare Run",
    "Capture 2 Rare or better species this week.",
    "weekly",
    "rare",
    2,
    220,
  ),
  rarityChallenge(
    "weekly-epic-expedition",
    "Epic Expedition",
    "Find an Epic or better species this week.",
    "weekly",
    "epic",
    1,
    260,
  ),
  createChallenge({
    slug: "weekly-fifteen-footprints",
    title: "Fifteen Footprints",
    description: "Capture 15 animals this week.",
    type: "weekly",
    targetCount: 15,
    xpReward: 190,
    conditionType: "capture_any",
  }),
  createChallenge({
    slug: "weekly-twenty-tracker",
    title: "Twenty Tracker",
    description: "Capture 20 animals this week.",
    type: "weekly",
    targetCount: 20,
    xpReward: 260,
    conditionType: "capture_any",
  }),
  classChallenge(
    "weekly-sky-census",
    "Sky Census",
    "Capture 5 bird species this week.",
    "weekly",
    "Aves",
    5,
    170,
  ),
  classChallenge(
    "weekly-mammal-marathon",
    "Mammal Marathon",
    "Capture 4 mammals this week.",
    "weekly",
    "Mammalia",
    4,
    160,
  ),
  classChallenge(
    "weekly-mammal-milestone",
    "Mammal Milestone",
    "Capture 6 mammals this week.",
    "weekly",
    "Mammalia",
    6,
    220,
  ),
  classChallenge(
    "weekly-bug-bonanza",
    "Bug Bonanza",
    "Capture 4 insects this week.",
    "weekly",
    "Insecta",
    4,
    150,
  ),
  classChallenge(
    "weekly-bug-barrage",
    "Bug Barrage",
    "Capture 6 insects this week.",
    "weekly",
    "Insecta",
    6,
    210,
  ),
  classChallenge(
    "weekly-frog-week",
    "Frog Week",
    "Capture 2 amphibians this week.",
    "weekly",
    "Amphibia",
    2,
    120,
  ),
  classChallenge(
    "weekly-reptile-route",
    "Reptile Route",
    "Capture 2 reptiles this week.",
    "weekly",
    "Reptilia",
    2,
    120,
  ),
  rarityChallenge(
    "weekly-shiny-week",
    "Shiny Week",
    "Capture 4 Uncommon or better species this week.",
    "weekly",
    "uncommon",
    4,
    150,
  ),
  rarityChallenge(
    "weekly-uncommon-uprising",
    "Uncommon Uprising",
    "Capture exactly 4 Uncommon species this week.",
    "weekly",
    "uncommon",
    4,
    180,
    true,
  ),
  rarityChallenge(
    "weekly-common-stack",
    "Common Stack",
    "Capture exactly 6 Common species this week.",
    "weekly",
    "common",
    6,
    140,
    true,
  ),
  createChallenge({
    slug: "weekly-rarity-sweep",
    title: "Rarity Sweep",
    description: "Collect at least one species of every rarity this week.",
    type: "weekly",
    targetCount: 5,
    xpReward: 250,
    conditionType: "collect_all_rarities",
  }),
  createChallenge({
    slug: "weekly-pocket-patrol",
    title: "Pocket Patrol",
    description: "Capture 8 animals this week.",
    type: "weekly",
    targetCount: 8,
    xpReward: 105,
    conditionType: "capture_any",
  }),
  createChallenge({
    slug: "weekly-wild-walk",
    title: "Wild Walk",
    description: "Capture 12 animals this week.",
    type: "weekly",
    targetCount: 12,
    xpReward: 155,
    conditionType: "capture_any",
  }),
];

const achievements: ChallengeTemplateRecord[] = [
  createChallenge({
    slug: "achievement-first-catch",
    title: "First Catch",
    description: "Capture your first species.",
    type: "achievement",
    targetCount: 1,
    xpReward: 50,
    conditionType: "capture_any",
  }),
  createChallenge({
    slug: "achievement-pocket-collection",
    title: "Pocket Collection",
    description: "Capture 5 species.",
    type: "achievement",
    targetCount: 5,
    xpReward: 80,
    conditionType: "capture_any",
  }),
  createChallenge({
    slug: "achievement-species-shelf",
    title: "Species Shelf",
    description: "Capture 10 species.",
    type: "achievement",
    targetCount: 10,
    xpReward: 120,
    conditionType: "capture_any",
  }),
  createChallenge({
    slug: "achievement-field-archivist",
    title: "Field Archivist",
    description: "Capture 25 species.",
    type: "achievement",
    targetCount: 25,
    xpReward: 220,
    conditionType: "capture_any",
  }),
  createChallenge({
    slug: "achievement-wildlife-ledger",
    title: "Wildlife Ledger",
    description: "Capture 50 species.",
    type: "achievement",
    targetCount: 50,
    xpReward: 350,
    conditionType: "capture_any",
  }),
  classChallenge(
    "achievement-sky-scout",
    "Sky Scout",
    "Capture your first bird species.",
    "achievement",
    "Aves",
    1,
    60,
  ),
  classChallenge(
    "achievement-mammal-scout",
    "Mammal Scout",
    "Capture your first mammal.",
    "achievement",
    "Mammalia",
    1,
    60,
  ),
  classChallenge(
    "achievement-bug-scout",
    "Bug Scout",
    "Capture your first insect.",
    "achievement",
    "Insecta",
    1,
    55,
  ),
  classChallenge(
    "achievement-frog-finder",
    "Frog Finder",
    "Capture your first amphibian.",
    "achievement",
    "Amphibia",
    1,
    65,
  ),
  classChallenge(
    "achievement-scale-spotter",
    "Scale Spotter",
    "Capture your first reptile.",
    "achievement",
    "Reptilia",
    1,
    65,
  ),
  classChallenge(
    "achievement-bird-atlas",
    "Bird Atlas",
    "Capture 5 bird species.",
    "achievement",
    "Aves",
    5,
    140,
  ),
  classChallenge(
    "achievement-mammal-atlas",
    "Mammal Atlas",
    "Capture 5 mammals.",
    "achievement",
    "Mammalia",
    5,
    150,
  ),
  classChallenge(
    "achievement-insect-index",
    "Insect Index",
    "Capture 5 insects.",
    "achievement",
    "Insecta",
    5,
    130,
  ),
  rarityChallenge(
    "achievement-bright-start",
    "Bright Start",
    "Capture your first Uncommon or better species.",
    "achievement",
    "uncommon",
    1,
    70,
  ),
  rarityChallenge(
    "achievement-rare-radar",
    "Rare Radar",
    "Capture your first Rare or better species.",
    "achievement",
    "rare",
    1,
    130,
  ),
  rarityChallenge(
    "achievement-epic-hunter",
    "Epic Hunter",
    "Capture your first Epic or better species.",
    "achievement",
    "epic",
    1,
    240,
  ),
  rarityChallenge(
    "achievement-legendary-hunter",
    "Legendary Hunter",
    "Capture your first Legendary species.",
    "achievement",
    "legendary",
    1,
    500,
    true,
  ),
  createChallenge({
    slug: "achievement-class-sampler",
    title: "Class Sampler",
    description: "Capture 3 different animal classes.",
    type: "achievement",
    targetCount: 3,
    xpReward: 140,
    conditionType: "capture_distinct_class",
  }),
  createChallenge({
    slug: "achievement-biodiversity-board",
    title: "Biodiversity Board",
    description: "Capture 5 different animal classes.",
    type: "achievement",
    targetCount: 5,
    xpReward: 280,
    conditionType: "capture_distinct_class",
  }),
  createChallenge({
    slug: "achievement-full-house",
    title: "Full House",
    description: "Collect at least one card of every rarity.",
    type: "achievement",
    targetCount: 5,
    xpReward: 300,
    conditionType: "collect_all_rarities",
  }),
  levelChallenge(
    "achievement-rookie-naturalist",
    "Rookie Naturalist",
    "Reach level 2.",
    2,
    60,
  ),
  levelChallenge(
    "achievement-field-adept",
    "Field Adept",
    "Reach level 3.",
    3,
    90,
  ),
  levelChallenge(
    "achievement-trail-scholar",
    "Trail Scholar",
    "Reach level 5.",
    5,
    160,
  ),
  levelChallenge(
    "achievement-habitat-hero",
    "Habitat Hero",
    "Reach level 7.",
    7,
    250,
  ),
  levelChallenge(
    "achievement-master-tracker",
    "Master Tracker",
    "Reach level 10.",
    10,
    400,
  ),
];

export const challengeCatalog = [
  ...dailyChallenges,
  ...weeklyChallenges,
  ...achievements,
];
